import React from 'react';

const NotesContent = () => {
  return (
    <div className="space-y-6">
      {/* Sensing & Acquisition */}
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h3 className="text-lg font-bold text-indigo-800 mb-4 border-b pb-2">Image Sensing & Acquisition</h3>
        <p className="text-sm text-gray-700 mb-3">Images are generated by the combination of an <strong>illumination source</strong> and the <strong>reflection/absorption</strong> of energy by objects in the scene.</p>
        <ul className="space-y-2 text-xs text-gray-600">
          <li>• <strong>Sensor Strips:</strong> Used in many flatbed scanners.</li>
          <li>• <strong>Sensor Arrays:</strong> Used in digital cameras (CCD/CMOS).</li>
        </ul>
      </div>

      {/* Sampling & Quantization */}
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h3 className="text-lg font-bold text-indigo-800 mb-4 border-b pb-2">Digitization: Sampling & Quantization</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <h4 className="font-semibold text-sm text-indigo-900">Sampling (Spatial)</h4>
            <p className="text-xs text-gray-700">Converting continuous coordinates into discrete ones. It determines the <strong>Spatial Resolution</strong>.</p>
            <div className="bg-red-50 p-2 rounded text-[10px] text-red-800 border border-red-100">
              <strong>Aliasing:</strong> Under-sampling causes high-frequency signals to appear as low-frequency artifacts.
            </div>
          </div>
          <div className="space-y-2">
            <h4 className="font-semibold text-sm text-indigo-900">Quantization (Tonal)</h4>
            <p className="text-xs text-gray-700">Converting continuous intensity levels into discrete values. It determines the <strong>Bit Depth</strong>.</p>
            <div className="bg-indigo-50 p-2 rounded text-[10px] text-indigo-800 border border-indigo-100">
              <strong>Dynamic Range:</strong> The ratio of the maximum measurable intensity to the minimum detectable level.
            </div>
          </div>
        </div>
      </div>

      {/* Color Spaces */}
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h3 className="text-lg font-bold text-indigo-800 mb-4 border-b pb-2">Color Models</h3>
        <div className="space-y-4">
          <div className="p-4 bg-gray-50 rounded border border-gray-200">
            <h4 className="font-semibold text-gray-800 text-sm mb-2">RGB (Red, Green, Blue)</h4>
            <p className="text-xs text-gray-600 mb-2">Additive model used in electronic displays. Based on human trichromatic vision.</p>
            <div className="grid grid-cols-3 gap-2 text-[10px] font-mono text-center">
              <div className="bg-white p-1 rounded border">Black: (0,0,0)</div>
              <div className="bg-white p-1 rounded border">White: (255,255,255)</div>
              <div className="bg-white p-1 rounded border text-red-600">Red: (255,0,0)</div>
              <div className="bg-white p-1 rounded border text-yellow-600">Yellow: (255,255,0)</div>
              <div className="bg-white p-1 rounded border text-cyan-600">Cyan: (0,255,255)</div>
              <div className="bg-white p-1 rounded border text-magenta-600">Magenta: (255,0,255)</div>
            </div>
          </div>
          <div className="p-4 bg-gray-50 rounded border border-gray-200">
            <h4 className="font-semibold text-gray-800 text-sm mb-2">HSV (Hue, Saturation, Value)</h4>
            <p className="text-xs text-gray-600">More intuitive for human manipulation.</p>
            <ul className="text-[10px] text-gray-500 list-disc list-inside">
              <li><strong>Hue:</strong> The "pure color" angle (0° to 360°).</li>
              <li><strong>Saturation:</strong> Purity or vividness (0% to 100%).</li>
              <li><strong>Value:</strong> Brightness or intensity.</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Types of Images */}
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
        <h3 className="text-lg font-bold text-indigo-800 mb-4 border-b pb-2">Types of Images</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-gray-50 text-gray-700 font-semibold uppercase text-[10px]">
              <tr>
                <th className="px-4 py-2">Type</th>
                <th className="px-4 py-2">Details</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 text-xs text-gray-600">
              <tr>
                <td className="px-4 py-3 font-medium text-indigo-700">Binary</td>
                <td className="px-4 py-3">1 bit/pixel (0 or 1). Black and White.</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium text-indigo-700">Grayscale</td>
                <td className="px-4 py-3">8 bits/pixel (0-255). Represents intensity.</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium text-indigo-700">Color (True Color)</td>
                <td className="px-4 py-3">24 bits/pixel (8 bits per R, G, B channel). ~16.7M colors.</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-medium text-indigo-700">Multispectral</td>
                <td className="px-4 py-3">Captures data at specific frequencies (e.g., Infrared). Used in satellite imagery.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default NotesContent;
